import { Config } from '../core/config.js';
import { SessionManager } from '../core/session.js';
import { RecallEngine } from '../engines/recall.js';
import { PersistenceEngine } from '../engines/persistence.js';
import { AugmentationEngine } from '../engines/augmentation.js';
import type { OpenClawIntegration } from '../integrations/openclaw.js';

/**
 * Internal dependency injection container passed to framework integrations.
 * Provides access to Memori's core engines and configuration state.
 * @internal
 */
export interface MemoriCore {
  recall: RecallEngine;
  persistence: PersistenceEngine;
  augmentation: AugmentationEngine;
  config: Config;
  session: SessionManager;
}

/**
 * Represents a single turn of conversation to be captured by Memori.
 * This payload is used by framework integrations to send user and agent messages
 * to the persistence and augmentation engines.
 */
export interface IntegrationRequest {
  /**
   * The raw text input provided by the user.
   * @example "What is my favorite color?"
   */
  userMessage: string;

  /**
   * The final text response generated by the AI agent.
   * @example "Based on your past messages, your favorite color is blue."
   */
  agentResponse: string;

  /**
   * Optional telemetry and contextual metadata about the LLM execution.
   */
  metadata?: IntegrationMetadata;
}

/**
 * Telemetry and execution metadata associated with a conversation turn.
 * Used by Memori's Augmentation Engine to track usage patterns, model performance,
 * and platform-specific metrics.
 */
export interface IntegrationMetadata {
  /**
   * The LLM provider used to generate the response.
   * @example 'openai', 'anthropic', 'openclaw'
   */
  provider: string | null | undefined;

  /**
   * The specific model identifier used for the completion.
   * @example 'gpt-4o', 'claude-3.5-sonnet'
   */
  model: string | null | undefined;

  /**
   * The version of the underlying LLM provider's SDK used, if available.
   * @example '4.28.0'
   */
  sdkVersion: string | null | undefined;

  /**
   * The version of the Memori integration or plugin capturing this data.
   * @example '1.0.0-openclaw-plugin'
   */
  integrationSdkVersion: string | null | undefined;

  /**
   * Theframework where the agent is running.
   * @example 'openclaw'
   */
  platform: string | null | undefined;
}

/**
 * A union type representing all officially supported framework integrations.
 * Used to strictly type the return value of the `memori.integrate()` method.
 */
export type SupportedIntegration = OpenClawIntegration;

/**
 * Constructor signature for a Memori integration class.
 * Ensures that all integrations can be instantiated with the `MemoriCore` DI container.
 * @typeParam T - The specific type of the integration being constructed
 */
export type IntegrationConstructor<T extends SupportedIntegration> = new (core: MemoriCore) => T;
